name: Deploy to Azure
on:
  release:
    types: [created]
env:
  AZURE_WEBAPP_NAME: BookClubWeb
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '3.1.101'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        - name: Build and Publish
          run: |
            dotnet build --configuration Release Web/BookClub/BookClub.csproj
            dotnet public -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish' src/BookClub/BookClub.csproj
        - name: Deploy to Azure
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/publish'
