name: .NET Core Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore Web/BookClub/BookClub.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore Web/BookClub/BookClub.csproj
