name: .NET

on:
  pull_request:
    branches: [ master, main ]

jobs:
  test-api-security-in-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: "5.0"
      - name: Test
        env:
          SLN_PATH: ${{ github.workspace }}/ApiSecurityInAction/dotnet/Natter.sln
        run: dotnet test ${{ env.SLN_PATH }}
